name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'No porszę, proszę... pierwsze Issue założone przez Ciebie! Tak trzymaj!'
        pr-message: 'To Twój pierwszy Pull Request, coż mamy powiedzieć - dziękujemy! Tak trzymaj!'
